### ISSUE TITLE
Jackson Databind 2.10.X StreamWriteFeature class not found 

### ISSUE THREAD

**Issue by mamup11** [FasterXML/jackson-core#571]
I'm having an issue with Jackson Databind 2.10.0, 2.10.0.pr1, 2.10.0.pr2 and 2.10.0.pr3 that is when executing my Spring application the `requestMappingHandlerAdapter` bean cannot be created due to the following missing class: 

```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamWriteFeature
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:489) ~[spring-core-5.1.10.RELEASE.jar:5.1.10.RELEASE]
	... 100 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.StreamWriteFeature
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	... 104 common frames omitted
```

With Jackson-Databind 2.9.10 the issue disappears but due to security vulnerabilities reported as `Deserialization of Untrusted Data` I'm not able to use that version.

**Comment by cowtowncoder** [comment]
You have a version mismatch somewhere: `jackson-core` has this class but only in version 2.10.0.
So perhaps you have older 2.9 version in classpath for some reason.

**Comment by rensuperk** [comment]
It seems works when I upgrade jackson version to 2.11.0
Thanks a lot!

 <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version.core}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version.core}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>${jackson.version.core}</version>
        </dependency>
